version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=common
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DBNAME=common
