name: first-web-demo-ci

on:
  push:
    branches-ignore:
      - 'deployment/develop'
      - 'deployment/product'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: setup go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: checkout source code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.32.2
  unit-test:
    strategy:
      matrix:
        go-version: [ 1.17.x , 1.18.x ]
        platform: [ ubuntu-latest ]

    runs-on: ${{matrix.platform}}
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      - name: checkout source code
        uses: actions/checkout@v3
      - name: run test
        run: go test ./...
